FROM node:20.18

RUN mkdir -p /home/node/app/node_modules

WORKDIR /home/node/app

RUN curl -sfS https://dotenvx.sh/install.sh | sh

COPY package*.json ./

RUN chown -R node:node /home/node/app

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 5555

CMD [ "dotenvx", "run", "--env-file=.env.local", "--", "node", "index.js" ]
