name: Deploy to Rasperry Pi 4

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: donjon-srv-raspberry-pi-4.duckdns.org
          ssh-port: 3066
      - name: Deploy to Raspberry Pi 4
        run: |
          ssh -o StrictHostKeyChecking=no -p 3066 donjon@donjon-srv-raspberry-pi-4.duckdns.org "cd git-repos/mern-stack-test && git pull && sudo docker compose --env-file ./.env.keys -f ./docker-compose.dev.yml up -d --build --force-recreate"
